language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator11.0

env:
  global:
    - NODE_VERSION=stable

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.npm
    - node_modules

install:
  - brew tap wix/brew
  - brew install applesimutils
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - cd examples
  - npm install
  - cd ..
  - npm install

  - gem install xcpretty

  - npm install -g react-native-cli
  - npm install -g detox-cli

script:
  - npm run tsc
  - cd examples
  - npm run tsc
  - cd ..
  - npm test
  - npm run lint
  - detox build --configuration ios.sim.release | xcpretty
  - detox test --configuration ios.sim.release --cleanup
