language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator11.0

env:
  global:
    - NODE_VERSION=stable

branches:
  only:
    - master

install:
  - brew tap wix/brew
  - brew install applesimutils
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - cd examples
  - yarn install
  - cd ..
  - yarn install

  - gem install xcpretty

  - yarn global add react-native-cli
  - yarn global add detox-cli

script:
  - yarn tsc
  - cd examples
  - yarn tsc
  - cd ..
  - yarn test
  - yarn lint
  - detox build --configuration ios.sim.release | xcpretty
  - detox test --configuration ios.sim.release --cleanup
