# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 12
    - nodejs_version: 10

version: "{build}"
build: off
deploy: off

branches:
  only:
    - master

cache:
  - node_modules

skip_commits:
  files:
    - "**/*.md"

install:
  - ps: Install-Product node $env:nodejs_version
  - cd examples
  - yarn install
  - cd ..
  - yarn install

test_script:
  - node --version
  - npm --version
  - yarn tsc
  - cd examples
  - yarn tsc
  - cd ..
  - yarn test
  - yarn lint
